#!/bin/bash

echo "================================================"
echo "Supporting Documents Setup"
echo "================================================"
echo ""
echo "To enable supporting documents for referrals, follow these steps:"
echo ""
echo "1. CREATE STORAGE BUCKET"
echo "   - Go to: https://supabase.com/dashboard/project/[your-project]/storage/buckets"
echo "   - Click 'New bucket'"
echo "   - Name: referral-documents"
echo "   - Set as PRIVATE"
echo "   - Click 'Create bucket'"
echo ""
echo "2. RUN DATABASE MIGRATION"
echo "   - Go to: https://supabase.com/dashboard/project/[your-project]/sql"
echo "   - Run this SQL:"
echo ""
echo "   ALTER TABLE referrals ADD COLUMN IF NOT EXISTS supporting_documents TEXT[] DEFAULT '{}';"
echo ""
echo "3. SET UP STORAGE POLICIES"
echo "   - In SQL Editor, run:"
echo ""
echo "   -- Allow anyone to upload"
echo "   CREATE POLICY \"Anyone can upload referral documents\""
echo "   ON storage.objects FOR INSERT"
echo "   TO anon, authenticated"
echo "   WITH CHECK (bucket_id = 'referral-documents');"
echo ""
echo "   -- Allow authenticated to view"
echo "   CREATE POLICY \"Authenticated users can view referral documents\""
echo "   ON storage.objects FOR SELECT"
echo "   TO authenticated"
echo "   USING (bucket_id = 'referral-documents');"
echo ""
echo "   -- Allow authenticated to delete"
echo "   CREATE POLICY \"Authenticated users can delete referral documents\""
echo "   ON storage.objects FOR DELETE"
echo "   TO authenticated"
echo "   USING (bucket_id = 'referral-documents');"
echo ""
echo "4. TEST THE FEATURE"
echo "   - Go to http://localhost:3000/referrals"
echo "   - Fill out form and upload test documents"
echo "   - Check admin panel to see uploaded files"
echo ""
echo "================================================"
echo "For more details, see SUPPORTING_DOCUMENTS_SETUP.md"
echo "================================================"
